# Generated by Django 3.1.6 on 2021-03-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_s_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_file',
        ),
    ]
