# Generated by Django 3.1.6 on 2021-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='expiry_date',
            field=models.TimeField(),
        ),
    ]
