# Generated by Django 3.1.6 on 2021-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='id',
        ),
        migrations.AlterField(
            model_name='authentication',
            name='token',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
