# Generated by Django 3.1.6 on 2021-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210319_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
