# Generated by Django 3.1.6 on 2021-03-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210319_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
